<?php

/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function news_accounts_form_alter(&$form, $form_state, $form_id) {
  // Look for any form provided by the contact module.
  // If you want to target a specific form you'll use the whole form ID
  // (e.g. Website feedback = 'contact_message_feedback_form').
  if (strpos($form_id, 'contact_message_') !== FALSE) {
    unset($form['actions']['preview']);
  }
}